# Generated by Django 4.0.4 on 2022-04-12 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_movie_theatre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatre',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.movie'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=120)),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.theatre')),
            ],
        ),
    ]
