# Generated by Django 4.0.4 on 2022-04-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_theatre_movie_timeslot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='City',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='theatre',
        ),
        migrations.DeleteModel(
            name='Theatre',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
