# Generated by Django 4.0.4 on 2022-04-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_movie_theatre_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ornage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
