# Generated by Django 4.0.4 on 2022-04-14 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_ornage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('booking_status', models.BooleanField(default='False')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.theatre')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.timeslot')),
            ],
        ),
        migrations.DeleteModel(
            name='ornage',
        ),
    ]
