# Generated by Django 4.0.4 on 2022-04-14 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_seats_delete_ornage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seats',
            new_name='Seat',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='name',
            new_name='number',
        ),
    ]
